version: "3"

services:
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - elk

  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.13.3
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01-test:9200"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    container_name: ls01-test
    image: docker.elastic.co/logstash/logstash:7.13.3
    volumes:
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "12201:12201/tcp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge
